"""initial schema v0.3

Revision ID: b589c60bb1d4
Revises: 
Create Date: 2026-09-15 16:13:53.198839
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = 'b589c60bb1d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('actor_label', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_audit_org_created', ['org_id', 'created_at'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('quotas', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('usage_counters',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('metric', sa.String(length=48), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'metric', 'day', name='uq_usage')
    )
    with op.batch_alter_table('usage_counters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_counters_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_counters_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_counters_org_id'), ['org_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sso_provider', sa.String(length=64), nullable=False),
    sa.Column('sso_subject', sa.String(length=320), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('last_login_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('webhook_id', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_webhook_id'), ['webhook_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('allowed_ips', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('last_used_at', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.Float(), nullable=True),
    sa.Column('revoked_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_org_id'), ['org_id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_membership')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_project_org_name')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_org_id'), ['org_id'], unique=False)

    op.create_table('webhooks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('secret', sa.String(length=128), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhooks_org_id'), ['org_id'], unique=False)

    op.create_table('agents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_project_id'), ['project_id'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('suite', sa.String(length=64), nullable=False),
    sa.Column('tasks', sa.JSON(), nullable=False),
    sa.Column('split', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_project_id'), ['project_id'], unique=False)

    op.create_table('deployments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=200), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('baseline_agent_id', sa.String(length=64), nullable=True),
    sa.Column('eval_run_id', sa.String(length=64), nullable=True),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('decision', sa.JSON(), nullable=False),
    sa.Column('promoted', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployments_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_project_id'), ['project_id'], unique=False)

    op.create_table('eval_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=True),
    sa.Column('suite', sa.String(length=64), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False),
    sa.Column('judge_model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('by_family', sa.JSON(), nullable=False),
    sa.Column('by_env', sa.JSON(), nullable=False),
    sa.Column('by_difficulty', sa.JSON(), nullable=False),
    sa.Column('by_role', sa.JSON(), nullable=False),
    sa.Column('n_tasks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_runs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_runs_project_id'), ['project_id'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('outcomes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_project_id'), ['project_id'], unique=False)

    op.create_table('intelligence_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=200), nullable=True),
    sa.Column('recent_hours', sa.Float(), nullable=False),
    sa.Column('baseline_hours', sa.Float(), nullable=False),
    sa.Column('n_recent', sa.Integer(), nullable=False),
    sa.Column('n_baseline', sa.Integer(), nullable=False),
    sa.Column('healthy', sa.Boolean(), nullable=False),
    sa.Column('drift', sa.JSON(), nullable=False),
    sa.Column('failures', sa.JSON(), nullable=False),
    sa.Column('coverage', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intelligence_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intelligence_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_reports_project_id'), ['project_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('logs', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('worker', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_jobs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('metric_points',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=200), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_points_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index('ix_metric_points_lookup', ['project_id', 'agent_name', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_points_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_points_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_points_ts'), ['ts'], unique=False)

    op.create_table('rollouts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('env_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('task_success', sa.Float(), nullable=True),
    sa.Column('total_reward', sa.Float(), nullable=False),
    sa.Column('record', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('eval_run_id', sa.String(length=64), nullable=True),
    sa.Column('training_run_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rollouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rollouts_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rollouts_eval_run_id'), ['eval_run_id'], unique=False)
        batch_op.create_index('ix_rollouts_project_created', ['project_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rollouts_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rollouts_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rollouts_training_run_id'), ['training_run_id'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('rollout_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_scores_project_name', ['project_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_rollout_id'), ['rollout_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_trace_id'), ['trace_id'], unique=False)

    op.create_table('traces',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('service', sa.String(length=200), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('n_spans', sa.Integer(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('rollout_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.create_index('ix_traces_project_created', ['project_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_traces_project_start', ['project_id', 'start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_rollout_id'), ['rollout_id'], unique=False)

    op.create_table('training_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('output_agent_id', sa.String(length=64), nullable=True),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_runs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_runs_project_id'), ['project_id'], unique=False)

    op.create_table('spans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('parent_span_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spans_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index('ix_spans_trace_start', ['trace_id', 'start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spans', schema=None) as batch_op:
        batch_op.drop_index('ix_spans_trace_start')
        batch_op.drop_index(batch_op.f('ix_spans_trace_id'))

    op.drop_table('spans')
    with op.batch_alter_table('training_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_training_runs_agent_id'))

    op.drop_table('training_runs')
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traces_rollout_id'))
        batch_op.drop_index('ix_traces_project_start')
        batch_op.drop_index(batch_op.f('ix_traces_project_id'))
        batch_op.drop_index('ix_traces_project_created')

    op.drop_table('traces')
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_trace_id'))
        batch_op.drop_index(batch_op.f('ix_scores_rollout_id'))
        batch_op.drop_index('ix_scores_project_name')
        batch_op.drop_index(batch_op.f('ix_scores_project_id'))

    op.drop_table('scores')
    with op.batch_alter_table('rollouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rollouts_training_run_id'))
        batch_op.drop_index(batch_op.f('ix_rollouts_task_id'))
        batch_op.drop_index(batch_op.f('ix_rollouts_project_id'))
        batch_op.drop_index('ix_rollouts_project_created')
        batch_op.drop_index(batch_op.f('ix_rollouts_eval_run_id'))
        batch_op.drop_index(batch_op.f('ix_rollouts_agent_id'))

    op.drop_table('rollouts')
    with op.batch_alter_table('metric_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_points_ts'))
        batch_op.drop_index(batch_op.f('ix_metric_points_project_id'))
        batch_op.drop_index(batch_op.f('ix_metric_points_name'))
        batch_op.drop_index('ix_metric_points_lookup')
        batch_op.drop_index(batch_op.f('ix_metric_points_agent_name'))

    op.drop_table('metric_points')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status_created')
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('intelligence_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intelligence_reports_project_id'))
        batch_op.drop_index(batch_op.f('ix_intelligence_reports_created_at'))

    op.drop_table('intelligence_reports')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_project_id'))

    op.drop_table('experiments')
    with op.batch_alter_table('eval_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_eval_runs_agent_id'))

    op.drop_table('eval_runs')
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployments_project_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_agent_name'))

    op.drop_table('deployments')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_project_id'))

    op.drop_table('datasets')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_project_id'))
        batch_op.drop_index(batch_op.f('ix_agents_name'))

    op.drop_table('agents')
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhooks_org_id'))

    op.drop_table('webhooks')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_org_id'))

    op.drop_table('projects')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_org_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_org_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_webhook_id'))

    op.drop_table('webhook_deliveries')
    op.drop_table('users')
    with op.batch_alter_table('usage_counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_counters_org_id'))
        batch_op.drop_index(batch_op.f('ix_usage_counters_metric'))
        batch_op.drop_index(batch_op.f('ix_usage_counters_day'))

    op.drop_table('usage_counters')
    op.drop_table('organizations')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_org_created')
        batch_op.drop_index(batch_op.f('ix_audit_log_org_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
